"""
Submission Models
================
Track user submissions for practice problems.
"""

from datetime import datetime
from typing import Optional, List
from beanie import Document
from pydantic import Field, BaseModel


class TestCase(BaseModel):
    """Single test case for a problem."""
    input_data: str
    expected_output: str
    is_sample: bool = False  # Sample test cases shown to user
    execution_time_ms: Optional[int] = None
    memory_kb: Optional[int] = None


class Submission(Document):
    """
    User submission for a practice problem.
    """
    
    # User & Problem Info
    user_id: str = Field(..., index=True)
    problem_id: str  # Codeforces ID like "1234A"
    problem_name: str
    problem_rating: Optional[int] = None
    
    # Submission Details
    source_code: str
    language: str = "python3"  # python3, cpp, java, etc.
    
    # Test Cases (Generated by LLM)
    test_cases: List[TestCase] = Field(default_factory=list)
    total_test_cases: int = 0
    passed_test_cases: int = 0
    
    # Verdict
    verdict: str  # AC, WA, TLE, MLE, RE, CE
    verdict_message: Optional[str] = None
    
    # Execution Stats
    execution_time_ms: int = 0
    memory_used_kb: int = 0
    
    # Failed Test Case Info (for WA)
    failed_on_test: Optional[int] = None
    failed_input: Optional[str] = None
    failed_expected: Optional[str] = None
    failed_actual: Optional[str] = None
    
    # Timestamps
    submitted_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    
    class Settings:
        name = "submissions"
        use_state_management = True


class UserProblemStatus(Document):
    """
    Track user's status on each problem (for solved/unsolved tracking).
    """
    
    user_id: str = Field(..., index=True)
    problem_id: str = Field(..., index=True)
    
    # Status
    is_solved: bool = False
    attempts: int = 0
    
    # Best Submission
    best_submission_id: Optional[str] = None
    best_execution_time_ms: Optional[int] = None
    
    # Timestamps
    first_attempt_at: datetime = Field(default_factory=datetime.utcnow)
    solved_at: Optional[datetime] = None
    last_attempt_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Settings:
        name = "user_problem_status"
        use_state_management = True
        indexes = [
            [("user_id", 1), ("problem_id", 1)]  # Compound index
        ]
